name: Nix flake check

on:
  push:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v26

    - name: Run nix flake check
      run: nix flake check
